apiVersion: v1 
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 2
    seector:
      matchLabels:
       app: backend
    template:
      metadata:
        labels: 
          app: backend
      spec:
        containers:
        - name: cont1
          image: abhipraydh96/b31-backend
